[GitHub Release] Polish workflow code (#32)
- Split the `github-release` stage into `publish-github-release` and `create-github-release`
- Replace the `checkout` task with passing `--repo` argument to GitHub CLI for the `publicize-github-release` and `check-release-exists` stages
- Add a description to all workflow inputs
- Rename `testing` input to `test_run`
- Format workflow according to guidelines
- Updated notifications messages to use workflow commands so that useful information will pop up on the workflow's annotation block

diff --git a/.github/workflows/_github-release.yml b/.github/workflows/_github-release.yml
--- a/.github/workflows/_github-release.yml
+++ b/.github/workflows/_github-release.yml
@@ -2,9 +2,10 @@
 # Create a new release on GitHub and include any artifacts in the `/dist` directory of the GitHUb artifacts store.
 #
 # Inputs:
-#  sha: the commit to attach to this release
-#  version_number: version number for the release (ex: 1.2.3rc2)
-#  file_uploads: Newline-delimited globs of paths to assets to upload for release
+#  sha:            The commit to attach to this release
+#  version_number: The release version number (i.e. 1.0.0b1, 1.2.3rc2, 1.0.0)
+#  changelog_path: Path to the changelog file for release notes
+#  test_run:       Test run (Publish release as draft)
 #
 # **why?**
 # Reusable and consistent GitHub release process.
@@ -27,16 +28,19 @@ on:
   workflow_call:
     inputs:
       sha:
+        description: The commit to attach to this release
         required: true
         type: string
       version_number:
+        description: The release version number (i.e. 1.0.0b1)
         required: true
         type: string
       changelog_path:
         description: Path to the changelog file for release notes
         required: true
         type: string
-      testing:
+      test_run:
+        description: Test run (Publish release as draft)
         required: true
         type: string
     outputs:
@@ -47,16 +51,22 @@ on:
 permissions:
   contents: write
 
+env:
+  REPO_LINK: ${{ github.server_url }}/${{ github.repository }}
+  NOTIFICATION_PREFIX: "[GitHub Release]"
+
 jobs:
   log-inputs:
     runs-on: ubuntu-latest
     steps:
-      - name: Print variables
+      - name: "[DEBUG] Print Variables"
         run: |
           echo The last commit sha in the release: ${{ inputs.sha }}
-          echo The release version number: ${{ inputs.version_number }}
-          echo Expected Changlog path: ${{ inputs.changelog_path }}
-          echo testing: ${{ inputs.testing }}
+          echo The release version number:         ${{ inputs.version_number }}
+          echo Expected Changlog path:             ${{ inputs.changelog_path }}
+          echo Test run:                           ${{ inputs.test_run }}
+          echo Repo link:                          ${{ env.REPO_LINK }}
+          echo Notification prefix:                ${{ env.NOTIFICATION_PREFIX }}
 
   check-release-exists:
     runs-on: ubuntu-latest
@@ -66,12 +76,9 @@ jobs:
       tag: ${{ steps.set_tag.outputs.tag }}
 
     steps:
-      - name: Generate Tag in Expected format
+      - name: "Generate Release Tag"
         id: set_tag
         run: echo "tag=v${{ inputs.version_number }}" >> $GITHUB_OUTPUT
-
-      - name: Check out the repository
-        uses: actions/checkout@v3
 
       # When the GitHub CLI doesn't find a release for the given tag, it will exit 1 with a
       # message of "release not found".  In our case, it's not an actual error, just a
@@ -80,44 +87,51 @@ jobs:
       # Also check if the release already exists is draft state.  If it does, and we are not
       # testing then we can publish that draft as is.  If it's in draft and we are testing, skip the
       # release.
-      - name: Check if release exists for tag
+      - name: "Check If Release Exists For Tag ${{ steps.set_tag.outputs.tag }}"
         id: release_check
         run: |
-          output=$((gh release view ${{ steps.set_tag.outputs.tag }} --json isDraft,targetCommitish) 2>&1) || true
+          output=$((gh release view ${{ steps.set_tag.outputs.tag }} --json isDraft,targetCommitish --repo ${{ env.REPO_LINK }}) 2>&1) || true
           if [[ "$output" == "release not found" ]]
           then
-            echo Release for tag ${{ steps.set_tag.outputs.tag }} does not exist
+            title="Release for tag ${{ steps.set_tag.outputs.tag }} does not exist."
+            message="Check passed."
             echo "exists=false" >> $GITHUB_OUTPUT
             echo "draft_exists=false" >> $GITHUB_OUTPUT
+            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
             exit 0
           fi
           commit=$(jq -r '.targetCommitish' <<< "$output")
           if [[ $commit != ${{ inputs.sha }} ]]
           then
-            echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists for commit $commit!
-            echo Cannot create a new release for commit ${{ inputs.sha }}.  Exiting.
+            title="Release for tag ${{ steps.set_tag.outputs.tag }} already exists for commit $commit!"
+            message="Cannot create a new release for commit ${{ inputs.sha }}. Exiting."
+            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
             exit 1
           fi
           isDraft=$(jq -r '.isDraft' <<< "$output")
-          if [[ $isDraft == true ]] && [[ ${{ inputs.testing }} == false ]]
+          if [[ $isDraft == true ]] && [[ ${{ inputs.test_run }} == false ]]
           then
-            echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists in draft form.  Need to Publish.
+            title="Release tag ${{ steps.set_tag.outputs.tag }} already associated with the draft release."
+            message="Release workflow will publish the associated release."
             echo "exists=false" >> $GITHUB_OUTPUT
             echo "draft_exists=true" >> $GITHUB_OUTPUT
+            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
             exit 0
           fi
-          echo Release for tag ${{ steps.set_tag.outputs.tag }} already exists.  Skip GitHub release.
+          title="Release for tag ${{ steps.set_tag.outputs.tag }} already exists."
+          message="Skip GitHub Release Publishing."
           echo "exists=true" >> $GITHUB_OUTPUT
           echo "draft_exists=false" >> $GITHUB_OUTPUT
-
+          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REPO: ${{ env.REPO_LINK }}
 
-      - name: Log Job Outputs
+      - name: "[DEBUG] Log Job Outputs"
         run: |
-          echo exists: ${{ steps.release_check.outputs.exists }}
+          echo exists:       ${{ steps.release_check.outputs.exists }}
           echo draft_exists: ${{ steps.release_check.outputs.draft_exists }}
-          echo tag: ${{ steps.set_tag.outputs.tag }}
+          echo tag:          ${{ steps.set_tag.outputs.tag }}
 
   skip-github-release:
     runs-on: ubuntu-latest
@@ -125,8 +139,11 @@ jobs:
     if: needs.check-release-exists.outputs.exists == 'true'
 
     steps:
-      - name: Tag Exists, Skip GitHub Release Job
-        run: echo A tag already exists for ${{ needs.check-release-exists.outputs.tag }} and commit, skipping release
+      - name: "Tag Exists, Skip GitHub Release Job"
+        run: |
+          echo title="A tag already exists for ${{ needs.check-release-exists.outputs.tag }} and commit."
+          echo message="Skipping GitHub release."
+          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
 
   audit-release-different-commit:
     runs-on: ubuntu-latest
@@ -134,81 +151,94 @@ jobs:
     if: needs.check-release-exists.outputs.exists == 'false'
 
     steps:
-      - name: Check if release already exists for commit
+      - name: "Check If Release Already Exists For Commit"
         uses: cardinalby/git-get-release-action@v1
         id: check_release_commit
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          commitSha: ${{inputs.sha}}
+          commitSha: ${{ inputs.sha }}
           doNotFailIfNotFound: true # returns blank outputs when not found instead of error
           searchLimit: 15 # Since we only care about recent releases, speed up the process
 
-      - name: Print Release Details
+      - name: "[DEBUG] Print Release Details"
         run: |
-          echo steps.check_release_commit.outputs.id ${{ steps.check_release_commit.outputs.id}}
-          echo steps.check_release_commit.outputs.tag_name ${{ steps.check_release_commit.outputs.tag_name}}
-          echo steps.check_release_commit.outputs.target_commitish ${{ steps.check_release_commit.outputs.target_commitish}}
-          echo steps.check_release_commit.outputs.prerelease ${{ steps.check_release_commit.outputs.prerelease}}
+          echo steps.check_release_commit.outputs.id:               ${{ steps.check_release_commit.outputs.id }}
+          echo steps.check_release_commit.outputs.tag_name:         ${{ steps.check_release_commit.outputs.tag_name }}
+          echo steps.check_release_commit.outputs.target_commitish: ${{ steps.check_release_commit.outputs.target_commitish }}
+          echo steps.check_release_commit.outputs.prerelease:       ${{ steps.check_release_commit.outputs.prerelease }}
 
       # Since we already know a release for this tag does not exist, if we find anything it's for the wrong tag, exit
-      - name: Check if the tag matches the version number
+      - name: "Check If The Tag Matches The Version Number"
         if: steps.check_release_commit.outputs.id != ''
         run: |
-          echo Tag "${{ steps.check_release_commit.outputs.tag_name}}" already exists for this commit!
-          echo Cannot create a new tag for "${{ needs.check-release-exists.outputs.tag }}" for the same commit.
+          title="Tag ${{ steps.check_release_commit.outputs.tag_name }} already exists for this commit!"
+          message="Cannot create a new tag for ${{ needs.check-release-exists.outputs.tag }} for the same commit"
+          echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
           exit 1
 
-  github-release:
+  publish-draft-release:
     runs-on: ubuntu-latest
     needs: [check-release-exists, audit-release-different-commit]
+    if: inputs.test_run  == 'false' && needs.check-release-exists.outputs.draft_exists == 'true'
 
     steps:
-      - name: Check out the repository
+      - name: "Publish Draft Release - ${{ needs.check-release-exists.outputs.tag }}"
+        run: |
+          gh release edit $TAG --draft=false --repo ${{ env.REPO_LINK }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ needs.check-release-exists.outputs.tag }}
+
+  create-github-release:
+    runs-on: ubuntu-latest
+    needs: [check-release-exists, audit-release-different-commit]
+    if: needs.check-release-exists.outputs.draft_exists == 'false'
+
+    steps:
+      - name: "Checkout ${{ github.repository }} Commit ${{ inputs.sha }}"
         uses: actions/checkout@v3
         with:
           ref: ${{ inputs.sha }}
 
-      - uses: actions/download-artifact@v3
+      - name: "Download Artifact ${{ inputs.version_number }} To dist Folder"
+        uses: actions/download-artifact@v3
         with:
           name: ${{ inputs.version_number }}
           path: "dist/"
 
-      - name: Display structure of all downloaded files
+      - name: "[DEBUG] Display Structure Of All Downloaded Files"
         run: ls -R
 
-      - name: Set release type
+      - name: "Set Release Type"
         id: release_type
         run: |
           if ${{ contains(inputs.version_number, 'rc') ||  contains(inputs.version_number, 'b') }}
           then
-            echo This is a prerelease
+            echo Release will be set as pre-release
             echo "prerelease=--prerelease" >> $GITHUB_OUTPUT
           else
             echo This is not a prerelease
           fi
 
-      - name: Set as draft release
+      - name: "Set As Draft Release"
         id: draft
         run: |
-          if [[ ${{ inputs.testing }} == true ]]
+          if [[ ${{ inputs.test_run }} == true ]]
           then
-            echo This is a draft release
+            echo Release will be published as draft
             echo "draft=--draft" >> $GITHUB_OUTPUT 
           else
             echo This is not a draft release
           fi
 
-      - name: Publish a release that was previously a draft
-        if: inputs.testing  == 'false' && needs.check-release-exists.outputs.draft_exists == 'true'
+      - name: "GitHub Release Workflow Annotation"
         run: |
-          gh release edit $TAG --draft=false
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          TAG: ${{ needs.check-release-exists.outputs.tag }}
+          title="Release ${{ needs.check-release-exists.outputs.tag }}"
+          message="Configuration: ${{ steps.release_type.outputs.prerelease }} ${{ steps.draft.outputs.draft }}"
+          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
 
-      - name: Create New GitHub Release
-        if: needs.check-release-exists.outputs.draft_exists == 'false'
+      - name: "Create New GitHub Release - ${{ needs.check-release-exists.outputs.tag }}"
         run: |
           gh release create $TAG ./dist/* --title "$TITLE" --notes-file $RELEASE_NOTES --target $COMMIT $PRERELEASE $DRAFT
         env:
@@ -217,5 +247,5 @@ jobs:
           TITLE: ${{ github.event.repository.name }} ${{ needs.check-release-exists.outputs.tag }}
           RELEASE_NOTES: ${{ inputs.changelog_path }}
           COMMIT: ${{ inputs.sha }}
-          PRERELEASE: ${{ steps.release_type.outputs.prerelease}}
-          DRAFT: ${{ steps.draft.outputs.draft}}
+          PRERELEASE: ${{ steps.release_type.outputs.prerelease }}
+          DRAFT: ${{ steps.draft.outputs.draft }}
