[Release] Cumulative update (#49)
Version Bump and Changelog Generation:

- Code format fix;
- Switch "parse-semver" ref to use the latest changes;
- Other minor fixes;

Build:

- Code format fix;
- Switch "parse-semver" ref to use the latest changes;
- Other minor fixes;

GitHub Release:

- Code format fix;

PyPI Release:

- Uncomment workflow code;
- Rename "testing" to "test_run";
- Add the "Sanitize Package Name" step for testing against "release-test" repos;
- Switch ref for "dbt-labs/actions/py-package-info" action to test new functionality;
- Rework conditions for stages;
- Update workflow documentation to match implementation;
- Formate workflow code according to guidelines;
- Update notifications messages to use workflow commands so that useful information will pop up on the workflow's annotation block;
- Rename some steps/variables to make more sense;
- Other minor improvements.

Post Slack Notification:

- Add workflow implementation;
- Add documentation;

diff --git a/.github/workflows/pypi-release.yml b/.github/workflows/pypi-release.yml
--- a/.github/workflows/pypi-release.yml
+++ b/.github/workflows/pypi-release.yml
@@ -2,9 +2,9 @@
 # After releasing to GitHub, release to PyPI
 #
 # Inputs:
-#   tag: tag of release in the format v1.2.3rc1
-#   testing: true is releasing to test PyPI, otherwise false
-# 
+#   version_number: The release version number (i.e. 1.0.0b1, 1.2.3rc2, 1.0.0)
+#   test_run      : Test run (true - release to Test PyPI, false - release to PyPI)
+#
 # **why?**
 # Automate the release process
 #
@@ -12,147 +12,201 @@
 #  After successfully releasing to GitHub
 #
 # Assumptions
-#  1.  The name of the repository is the name of the package on PyPI
+#  1. The name of the repository is the name of the package on PyPI
 #
+# Validation Checks
+#  1. If the provided version is not uploaded to PyPI yet, release it.
+#  2. Release to test or prod package index, depending on the value of test_run input.
+#  3. Check PyPI at the end to validate that the version has been uploaded to package index.
 
 name: PyPI release
 
 on:
   workflow_call:
     inputs:
-      tag:
-        description: 'The tag for the release (ie. v1.0.0b1)'
+      version_number:
+        description: "The tag for the release (ie. v1.0.0b1)"
         required: true
         type: string
-      testing:
+      test_run:
         required: true
         type: string
     # pass through secrets for both PyPi Test and Prod so they're always there
-    # secrets:
-    #   PYPI_API_TOKEN:
-    #     description: AWS Access Key ID
-    #     required: true
-    #   TEST_PYPI_API_TOKEN:
-    #     description: Test Pypi api token
-    #     required: true
+    secrets:
+      PYPI_API_TOKEN:
+        description: PyPI API token
+        required: true
+      TEST_PYPI_API_TOKEN:
+        description: Test PyPI API token
+        required: true
 
 permissions:
   contents: read
+
+env:
+  NOTIFICATION_PREFIX: "[PyPI Release]"
 
 jobs:
   log-inputs:
     runs-on: ubuntu-latest
     steps:
-      - name: Print variables
+      - name: "[DEBUG] Print Variables"
         run: |
-            echo Tag: ${{ inputs.tag }}
-            echo Release to test PyPI: ${{ inputs.testing }}
+          echo The release version number: ${{ inputs.version_number }}
+          echo Release to test PyPI:       ${{ inputs.test_run }}
 
-  check-pypi-exists:
+  sanitize-package-name:
     runs-on: ubuntu-latest
+
     outputs:
-      exists: ${{ steps.set_existence.outputs.exists }}
-  
+      name: ${{ steps.package-name.outputs.name }}
+
     steps:
-      - name: Check PyPI
-        id: pypi_info
-        uses: dbt-labs/actions/py-package-info@v1
+      - name: "Sanitize Package Name"
+        id: package-name
+        run: |
+          repo_name=${{ github.event.repository.name }}
+          test_suffix="-release-test"
+          name=${repo_name%"$test_suffix"}
+          echo "name=$name" >> $GITHUB_OUTPUT
+
+  check-package-exists-pypi:
+    runs-on: ubuntu-latest
+    needs: [sanitize-package-name]
+
+    outputs:
+      exists: ${{ steps.version_existence.outputs.is_exists }}
+
+    steps:
+      - name: "Audit Version And Parse Into Parts"
+        id: semver
+        uses: dbt-labs/actions/parse-semver@dc183a8f07a756c6bb5e5fca63a2848b1fe781c8
         with:
-          package: ${{ github.event.repository.name }}
-          version: ${{ inputs.tag }}
-          # test: ${{ inputs.testing }}  TODO: implement in action
-      
-      - name: Set Outputs
-      # The above step will just use the latest version if the input version
-      # is not found.  So to validate the version we want to release exists
-      # we need to compare the output version.
-        id: set_existence
+          version: ${{ inputs.version_number }}
+
+      - name: "Fetch PyPI Info For ${{ steps.semver.outputs.version }} Package"
+        id: pypi_info
+        uses: dbt-labs/actions/py-package-info@c00eb536420d454ba5fdf90ac4571e360f0c7524
+        with:
+          package: ${{ needs.sanitize-package-name.outputs.name }}
+          version: ${{ steps.semver.outputs.version }}
+          check-test-index: ${{ inputs.test_run }}
+
+      - name: "Set Version Existence For Subsequent Jobs"
+        # The above step will just use the latest version if the input version
+        # is not found.  So to validate the version we want to release exists
+        # we need to compare the output version.
+        id: version_existence
         run: |
-          if [[ ${{ steps.pypi_info.outputs.version }} != ${{ inputs.tag }} ]]
+          is_exists=false
+          if [[ ${{ steps.pypi_info.outputs.version }} == ${{ inputs.version_number }} ]]
           then
-            echo PyPI Package not found for ${{ inputs.tag }}
-            echo '::set-output name=exists::false'
-          else
-            echo PyPI Package found for ${{ inputs.tag }}.  Skip release.
-            echo '::set-output name=exists::true'
+            is_exists=true
           fi
-      
-      - name: Temp Always fail.
-        run: |
-          echo exits: ${{ steps.set_existence.outputs.exists.outputs.exists}}
-          echo '::set-output name=exists::true'
+          echo "is_exists=$is_exists" >> $GITHUB_OUTPUT
 
   skip-pypi-release:
     runs-on: ubuntu-latest
-    needs: [check-pypi-exists]
-    if: needs.check-pypi-exists.outputs.exists == 'true'
+    needs: [sanitize-package-name, check-package-exists-pypi]
+    if: needs.check-package-exists-pypi.outputs.exists == 'true'
 
     steps:
-      - name: PyPI Release Exists, Skip
-        run: echo A release already exists for this version ${{ inputs.tag }} on Pypi, skipping
+      - name: "[Notification] Package Version Already Live In Package Index. Skip Upload."
+        run: |
+          title="Package version already live in package index"
+          version=${{ inputs.version_number }}
+          package_name=${{ needs.sanitize-package-name.outputs.name }}
+          package_index="PyPI"
+          if [[ ${{ inputs.test_run }} == true ]]
+          then
+            package_index="Test PyPi"
+          fi
+          message="The version $version of package $package_name already lives in the $package_index. The upload to the package index will be skipped."
+          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
 
-  # test-pypi-release:
-  #   runs-on: ubuntu-latest
-  #   needs: [check-pypi-exists]
-  #   if: needs.check-pypi-exists.outputs.exists == 'false' && ${{ inputs.testing }} == 'false'
-  
-  #   environment: PypiTest
-  #   steps:
-  #     - uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: 'dist'
+  test-pypi-release:
+    runs-on: ubuntu-latest
+    needs: [sanitize-package-name, check-package-exists-pypi]
+    if: >-
+      needs.check-package-exists-pypi.outputs.exists == 'false' &&
+      inputs.test_run == true
 
-  #     - name: Publish distribution to test PyPI
-  #       uses: pypa/gh-action-pypi-publish@v1.5
-  #       with:
-  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
-  #         repository_url: https://test.pypi.org/legacy/
+    environment: PypiTest
 
-  # prod-pypi-release:
-  #   runs-on: ubuntu-latest
-  #   needs: [check-pypi-exists]
-  #   if: needs.check-pypi-exists.outputs.exists == 'false'  && ${{ inputs.testing }} == 'true'
-  
-  #   environment: PypiProd
-  #   steps:
-  #     - uses: actions/download-artifact@v3
-  #       with:
-  #         name: dist
-  #         path: 'dist'
+    steps:
+      - name: "Download Build Artifact - ${{ inputs.version_number }}"
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ inputs.version_number }}
+          path: .
 
-  #     - name: Publish distribution to PyPI
-  #       if: ${{ inputs.testing }} == 'true'
-  #       uses: pypa/gh-action-pypi-publish@v1.5
-  #       with:
-  #         password: ${{ secrets.PYPI_API_TOKEN }}
+      - name: "Publish ${{ needs.sanitize-package-name.outputs.name }} v${{ inputs.version_number }} To Test PyPI"
+        uses: pypa/gh-action-pypi-publish@v1.6.4
+        with:
+          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
+          repository_url: https://test.pypi.org/legacy/
 
-  # validate-pypi-package:
-  #   runs-on: ubuntu-latest
-  #   needs: [test-pypi-release, prod-pypi-release]
-  #   # always run this step because one of the needs are always skipped.
-  #   if: always()
+  prod-pypi-release:
+    runs-on: ubuntu-latest
+    needs: [sanitize-package-name, check-package-exists-pypi]
+    if: >-
+      needs.check-package-exists-pypi.outputs.exists == 'false' &&
+      inputs.test_run == false
 
-  #   steps:
-  #     - name: Check PyPI
-  #       id: pypi_info
-  #       uses: dbt-labs/actions/py-package-info@v1
-  #       with:
-  #         package: ${{ github.event.repository.name }}
-  #         version: ${{ inputs.tag }}
-  #         # test: ${{ inputs.testing }}  TODO: implement in action
-      
-  #     - name: Set output
-  #     # The above step will just use the latest version if the input version
-  #     # is not found.  So to validate the version we want to release exists
-  #     # we need to compare teh output version.
-  #       id: set_existence
-  #       run: |
-  #         if [[ ${{ steps.pypi_info.version }} != ${{ inputs.tag }} ]]
-  #         then
-  #           echo ${{ inputs.tag }} released to Pypi
-  #         else
-  #           echo ${{ inputs.tag }} FAILED to released to Pypi.  Manual intervention required.
-  #           exit 1
-  #         fi
+    environment: PypiProd
 
+    steps:
+      - name: "Download Build Artifact - ${{ inputs.version_number }}"
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ inputs.version_number }}
+          path: .
+
+      - name: "Publish ${{ needs.sanitize-package-name.outputs.name }} v${{ inputs.version_number }} To PyPI"
+        uses: pypa/gh-action-pypi-publish@v1.6.4
+        with:
+          password: ${{ secrets.PYPI_API_TOKEN }}
+
+  validate-package-available-pypi:
+    runs-on: ubuntu-latest
+    needs: [sanitize-package-name, test-pypi-release, prod-pypi-release]
+    # always run this step because one of the needs are always skipped.
+    if: ${{ success() }}
+
+    steps:
+      - name: "Audit Version And Parse Into Parts"
+        id: semver
+        uses: dbt-labs/actions/parse-semver@dc183a8f07a756c6bb5e5fca63a2848b1fe781c8
+        with:
+          version: ${{ inputs.version_number }}
+
+      - name: "Fetch PyPI Info For ${{ needs.sanitize-package-name.outputs.name }} Package"
+        id: pypi_info
+        uses: dbt-labs/actions/py-package-info@c00eb536420d454ba5fdf90ac4571e360f0c7524
+        with:
+          package: ${{ needs.sanitize-package-name.outputs.name }}
+          version: ${{ steps.semver.outputs.version }}
+          check-test-index: ${{ inputs.test_run }}
+
+      - name: "Validate PyPI Info"
+        id: is-version-available
+        run: |
+          is_available=false
+          if [[ ${{ steps.pypi_info.outputs.version }} == ${{ steps.semver.outputs.version }} ]]
+          then
+            is_available=true
+          fi
+          echo "is_available=$is_available" >> $GITHUB_OUTPUT
+
+      - name: "Set Workflow Status"
+        run: |
+          title="Availability Validation"
+          if [[ ${{ steps.is-version-available.outputs.is_available }} == true ]]
+          then
+            message="The ${{ needs.sanitize-package-name.outputs.name }} v${{ steps.semver.outputs.version }} version available in PyPI."
+            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
+          else
+            message="The info about ${{ needs.sanitize-package-name.outputs.name }} v${{ steps.semver.outputs.version }} version is not available in PyPI. Manual intervention required."
+            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
+            exit 1
+          fi
