Update release-prep.yml

diff --git a/.github/workflows/release-prep.yml b/.github/workflows/release-prep.yml
--- a/.github/workflows/release-prep.yml
+++ b/.github/workflows/release-prep.yml
@@ -275,116 +275,116 @@ jobs:
         run: |
           echo branch_name ${{ steps.variables.outputs.branch_name }}
 
-  generate-changelog-bump-version:
-    runs-on: ubuntu-latest
-    needs: [audit-changelog, audit-version-in-code, create-temp-branch]
+  # generate-changelog-bump-version:
+  #   runs-on: ubuntu-latest
+  #   needs: [audit-changelog, audit-version-in-code, create-temp-branch]
 
-    steps:
-      - name: "Checkout ${{ github.repository }} Branch ${{ needs.create-temp-branch.outputs.branch_name }}"
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ needs.create-temp-branch.outputs.branch_name }}
+  #   steps:
+  #     - name: "Checkout ${{ github.repository }} Branch ${{ needs.create-temp-branch.outputs.branch_name }}"
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ needs.create-temp-branch.outputs.branch_name }}
 
-      - name: "Install Spark Dependencies"
-        if: ${{ github.repository == 'dbt-labs/dbt-spark-release-test' }}
-        run: |
-          sudo apt-get install libsasl2-dev
+  #     - name: "Install Spark Dependencies"
+  #       if: ${{ github.repository == 'dbt-labs/dbt-spark-release-test' }}
+  #       run: |
+  #         sudo apt-get install libsasl2-dev
 
-      - name: "Add Homebrew To PATH"
-        run: |
-          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
+  #     - name: "Add Homebrew To PATH"
+  #       run: |
+  #         echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
 
-      - name: "Install Homebrew Packages"
-        run: |
-          brew install pre-commit
-          brew tap miniscruff/changie https://github.com/miniscruff/changie
-          brew install changie
+  #     - name: "Install Homebrew Packages"
+  #       run: |
+  #         brew install pre-commit
+  #         brew tap miniscruff/changie https://github.com/miniscruff/changie
+  #         brew install changie
 
-      - name: "Generate Release Changelog"
-        if: needs.audit-changelog.outputs.exists == 'false'
-        run: |
-          if [[ ${{ needs.audit-changelog.outputs.is_prerelease }} -eq 1 ]]
-          then
-            changie batch ${{ needs.audit-changelog.outputs.base_version }} --move-dir '${{ needs.audit-changelog.outputs.base_version }}' --prerelease ${{ needs.audit-changelog.outputs.prerelease }}
-          else
-            changie batch ${{ needs.audit-changelog.outputs.base_version }} --include '${{ needs.audit-changelog.outputs.base_version }}' --remove-prereleases
-          fi
-          changie merge
-          git status
+  #     - name: "Generate Release Changelog"
+  #       if: needs.audit-changelog.outputs.exists == 'false'
+  #       run: |
+  #         if [[ ${{ needs.audit-changelog.outputs.is_prerelease }} -eq 1 ]]
+  #         then
+  #           changie batch ${{ needs.audit-changelog.outputs.base_version }} --move-dir '${{ needs.audit-changelog.outputs.base_version }}' --prerelease ${{ needs.audit-changelog.outputs.prerelease }}
+  #         else
+  #           changie batch ${{ needs.audit-changelog.outputs.base_version }} --include '${{ needs.audit-changelog.outputs.base_version }}' --remove-prereleases
+  #         fi
+  #         changie merge
+  #         git status
 
-      # this step will fail on whitespace errors but also correct them
-      - name: "Remove Trailing Whitespace Via Pre-commit"
-        continue-on-error: true
-        run: |
-          pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/*
-          git status
+  #     # this step will fail on whitespace errors but also correct them
+  #     - name: "Remove Trailing Whitespace Via Pre-commit"
+  #       continue-on-error: true
+  #       run: |
+  #         pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/*
+  #         git status
 
-      # this step will fail on newline errors but also correct them
-      - name: "Removing Extra Newlines Via Pre-commit"
-        continue-on-error: true
-        run: |
-          pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/*
-          git status
+  #     # this step will fail on newline errors but also correct them
+  #     - name: "Removing Extra Newlines Via Pre-commit"
+  #       continue-on-error: true
+  #       run: |
+  #         pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/*
+  #         git status
 
-      - name: "Check Changelog Created Successfully"
-        if: needs.audit-changelog.outputs.exists == 'false'
-        run: |
-          title="Changelog"
-          if [[ -f ${{ needs.audit-changelog.outputs.changelog_path }} ]]
-          then
-            message="Changelog file created successfully"
-            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
-          else
-            message="Changelog failed to generate"
-            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
-            exit 1
-          fi
+  #     - name: "Check Changelog Created Successfully"
+  #       if: needs.audit-changelog.outputs.exists == 'false'
+  #       run: |
+  #         title="Changelog"
+  #         if [[ -f ${{ needs.audit-changelog.outputs.changelog_path }} ]]
+  #         then
+  #           message="Changelog file created successfully"
+  #           echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
+  #         else
+  #           message="Changelog failed to generate"
+  #           echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
+  #           exit 1
+  #         fi
 
-      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ env.PYTHON_TARGET_VERSION }}
+  #     - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ env.PYTHON_TARGET_VERSION }}
 
-      - name: "Install Python Dependencies"
-        if: needs.audit-version-in-code.outputs.up_to_date == 'false'
-        run: |
-          python3 -m venv env
-          source env/bin/activate
-          python -m pip install --upgrade pip
+  #     - name: "Install Python Dependencies"
+  #       if: needs.audit-version-in-code.outputs.up_to_date == 'false'
+  #       run: |
+  #         python3 -m venv env
+  #         source env/bin/activate
+  #         python -m pip install --upgrade pip
 
-      - name: "Bump Version To ${{ inputs.version_number }}"
-        if: needs.audit-version-in-code.outputs.up_to_date == 'false'
-        # note: bumpversion is no longer supported, it actually points to bump2version now
-        run: |
-          source env/bin/activate
-          python -m pip install -r dev-requirements.txt
-          env/bin/bumpversion --allow-dirty --new-version ${{ inputs.version_number }} major
-          git status
+  #     - name: "Bump Version To ${{ inputs.version_number }}"
+  #       if: needs.audit-version-in-code.outputs.up_to_date == 'false'
+  #       # note: bumpversion is no longer supported, it actually points to bump2version now
+  #       run: |
+  #         source env/bin/activate
+  #         python -m pip install -r dev-requirements.txt
+  #         env/bin/bumpversion --allow-dirty --new-version ${{ inputs.version_number }} major
+  #         git status
 
-      - name: "[Notification] Bump Version To ${{ inputs.version_number }}"
-        if: needs.audit-version-in-code.outputs.up_to_date == 'false'
-        run: |
-          title="Version bump"
-          message="Version successfully bumped in codebase to ${{ inputs.version_number }}"
-          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
+  #     - name: "[Notification] Bump Version To ${{ inputs.version_number }}"
+  #       if: needs.audit-version-in-code.outputs.up_to_date == 'false'
+  #       run: |
+  #         title="Version bump"
+  #         message="Version successfully bumped in codebase to ${{ inputs.version_number }}"
+  #         echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
 
-      - name: "Commit & Push Changes"
-        run: |
-          #Data for commit
-          user="Github Build Bot"
-          email="buildbot@fishtownanalytics.com"
-          commit_message="Bumping version to ${{ inputs.version_number }} and generate changelog"
-          #Commit changes to branch
-          git config user.name "$user"
-          git config user.email "$email"
-          git pull
-          git add .
-          git commit -m "$commit_message"
-          git push
+  #     - name: "Commit & Push Changes"
+  #       run: |
+  #         #Data for commit
+  #         user="Github Build Bot"
+  #         email="buildbot@fishtownanalytics.com"
+  #         commit_message="Bumping version to ${{ inputs.version_number }} and generate changelog"
+  #         #Commit changes to branch
+  #         git config user.name "$user"
+  #         git config user.email "$email"
+  #         git pull
+  #         git add .
+  #         git commit -m "$commit_message"
+  #         git push
 
   run-unit-tests:
     runs-on: ubuntu-latest
-    needs: [create-temp-branch, generate-changelog-bump-version]
+    needs: [create-temp-branch] #, generate-changelog-bump-version]
 
     env:
       TOXENV: unit
@@ -417,7 +417,7 @@ jobs:
 
   run-integration-tests:
     runs-on: ubuntu-20.04
-    needs: [create-temp-branch, generate-changelog-bump-version]
+    needs: [create-temp-branch] #generate-changelog-bump-version]
     if: inputs.env_setup_script_path != ''
 
     env:
@@ -431,7 +431,9 @@ jobs:
 
       - name: view the secrets context
         shell: bash
-        run: echo "$SECRETS_CONTEXT"
+        run: |
+          echo "$SECRETS_CONTEXT"
+          echo $SECRETS_CONTEXT | jq -r 'to_entries[] | .key + "=\"" + (.value|tostring) + "\""
         env:
           SECRETS_CONTEXT: ${{ toJson(secrets) }}
 
